---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: Site
- type: document
  path: _config.yml
  label: Site Config
- type: document
  path: _data/navigation.yml
  label: Navigation
- type: directory
  path: news
  label: News
  create: all
  match: "**/*"
  new_doc_ext: md
- type: heading
  label: Comic
- type: directory
  path: comic
  label: Comic Pages
  create: all
  match: "**/*"
  new_doc_ext: md
- type: document
  path: _data/galleries.yml
  label: Image Galleries
  match: "**/*"
- type: heading
  label: Characters
- type: document
  path: _data/characters.yml
  label: Characters Info
- type: directory
  path: characters
  label: Add/remove character pages
  create: all
  match: "*"
  new_doc_ext: md
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    -d _site
