---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: Site
- type: document
  path: _config.yml
  label: Site Config
- type: document
  path: _data/navigation.yml
  label: Navigation
- type: document
  path: _data/newsbox.yml
  label: News box
- type: heading
  label: Pages
- type: document
  path: about.md
  label: About
- type: directory
  path: news
  label: News
  create: all
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: galleries
  label: Galleries
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - gallery-image
- type: document
  path: links.md
  label: Links
- type: heading
  label: Comic
- type: directory
  path: comic
  label: Comic Pages
  create: all
  match: "**/*"
  new_doc_ext: md
- type: heading
  label: Characters
- type: document
  path: _data/characters.yml
  label: Characters Info
- type: directory
  path: characters
  label: Add/remove character pages
  create: all
  match: "*"
  new_doc_ext: md
upload_dir: assets/img/galleries/bonus
public_path: assets/img/galleries/bonus
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    -d _site
