name: Generate thumbnails, build and deploy

on:
   push:
      branches:
         - main

jobs:
   build:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v3
         - uses: jruipinto/ImageMagick-action@v1
           name: "Generate thumbnails of pages from jpegs"
           continue-on-error: true
           with:
              # ImageMagick command to be executed
              command: mogrify -resize x250 -format webp assets/img/pages/*/*.jpeg
         - uses: jruipinto/ImageMagick-action@v1
           name: "Generate thumbnails of pages from jpgs"
           continue-on-error: true
           with:
              # ImageMagick command to be executed
              command: mogrify -resize x250 -format webp assets/img/pages/*/*.jpg
         - uses: jruipinto/ImageMagick-action@v1
           name: "Generate thumbnails of pages from pngs"
           continue-on-error: true
           with:
              # ImageMagick command to be executed
              command: mogrify -resize x250 -format webp assets/img/pages/*/*.png
         - uses: jruipinto/ImageMagick-action@v1
           name: "Generate thumbnails of pages from gifs"
           continue-on-error: true
           with:
              # ImageMagick command to be executed
              command: mogrify -resize x250 -format webp assets/img/pages/*/*.gif
         - uses: jruipinto/ImageMagick-action@v1
           name: "Generate thumbnails of gallery images from jpegs"
           continue-on-error: true
           with:
              # ImageMagick command to be executed
              command: mogrify -resize x250 -format webp assets/img/galleries/*/*.jpeg
         - uses: jruipinto/ImageMagick-action@v1
           name: "Generate thumbnails of gallery images from jpgs"
           continue-on-error: true
           with:
              # ImageMagick command to be executed
              command: mogrify -resize x250 -format webp assets/img/galleries/*/*.jpg
         - uses: jruipinto/ImageMagick-action@v1
           name: "Generate thumbnails of gallery images from pngs"
           continue-on-error: true
           with:
              # ImageMagick command to be executed
              command: mogrify -resize x250 -format webp assets/img/galleries/*/*.png
         - uses: jruipinto/ImageMagick-action@v1
           name: "Generate thumbnails of gallery images from gifs"
           continue-on-error: true
           with:
              # ImageMagick command to be executed
              command: mogrify -resize x250 -format webp assets/img/galleries/*/*.gif
         - uses: actions/cache@v2
           with:
              path: vendor/bundle
              key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
              restore-keys: |
                 ${{ runner.os }}-gems-
         - uses: helaili/jekyll-action@v2
           with:
              token: ${{ secrets.GITHUB_TOKEN }}
              target_branch: "build"
              keep_history: true
   deploy:
      needs: build
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v3
           with:
              ref: build
         - name: FTP-Deploy-Action
           uses: SamKirkland/FTP-Deploy-Action@4.3.0
           with:
              server: ${{ secrets.FTP_SERVER }}
              username: ${{ secrets.FTP_USERNAME }}
              password: ${{ secrets.FTP_PASSWORD }}
