name: Build

on:
   push:
      branches:
         - main

jobs:
   build:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v1
         - uses: jruipinto/ImageMagick-action@v1
           name: "Generate thumbnails of pages from jpegs"
           continue-on-error: true
           with:
              # ImageMagick command to be executed
              command: mogrify -resize x250 -format webp assets/img/pages/*/*.jpeg
         - uses: jruipinto/ImageMagick-action@v1
           name: "Generate thumbnails of pages from pngs"
           continue-on-error: true
           with:
              # ImageMagick command to be executed
              command: mogrify -resize x250 -format webp assets/img/pages/*/*.png
         - uses: jruipinto/ImageMagick-action@v1
           name: "Generate thumbnails of pages from gifs"
           continue-on-error: true
           with:
              # ImageMagick command to be executed
              command: mogrify -resize x250 -format webp assets/img/pages/*/*.gif
         - uses: jruipinto/ImageMagick-action@v1
           name: "Generate thumbnails of gallery images from jpegs"
           continue-on-error: true
           with:
              # ImageMagick command to be executed
              command: mogrify -resize x250 -format webp assets/img/galleries/*/*.jpeg
         - uses: jruipinto/ImageMagick-action@v1
           name: "Generate thumbnails of gallery images from jpgs"
           continue-on-error: true
           with:
              # ImageMagick command to be executed
              command: mogrify -resize x250 -format webp assets/img/galleries/*/*.jpg
         - uses: jruipinto/ImageMagick-action@v1
           name: "Generate thumbnails of gallery images from pngs"
           continue-on-error: true
           with:
              # ImageMagick command to be executed
              command: mogrify -resize x250 -format webp assets/img/galleries/*/*.png
         - uses: jruipinto/ImageMagick-action@v1
           name: "Generate thumbnails of gallery images from gifs"
           continue-on-error: true
           with:
              # ImageMagick command to be executed
              command: mogrify -resize x250 -format webp assets/img/galleries/*/*.gif
         - name: Commit generated thumbnails
           run: |
              git config --global user.name 'Jasmine Chatfield'
              git config --global user.email 'jasminechatfield@users.noreply.github.com'
              git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
              git checkout "${GITHUB_REF:11}"
              git commit --allow-empty -am "Thumbnails"
              git push
         - uses: actions/cache@v2
           with:
              path: vendor/bundle
              key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
              restore-keys: |
                 ${{ runner.os }}-gems-
         - uses: helaili/jekyll-action@v2
           with:
              token: ${{ secrets.GITHUB_TOKEN }}
              target_branch: "gh-pages"
   FTP-Deploy-Action:
      name: FTP-Deploy-Action
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v2.1.0
           with:
              ref: gh-pages
              fetch-depth: 2
         - name: FTP-Deploy-Action
           uses: SamKirkland/FTP-Deploy-Action@3.1.1
           with:
              ftp-server: ${{ secrets.FTP_SERVER }}
              ftp-username: ${{ secrets.FTP_USERNAME }}
              ftp-password: ${{ secrets.FTP_PASSWORD }}
