name: Generate thumbnails

on:
   push:
      branches:
         - main

jobs:
   build:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v1
         - uses: jruipinto/ImageMagick-action@v1
           with:
              # ImageMagick command to be executed
              command: mogrify -resize x250 -format webp assets/img/pages/*/*.jpeg
         - uses: jruipinto/ImageMagick-action@v1
           with:
              # ImageMagick command to be executed
              command: mogrify -resize x250 -format webp assets/img/pages/*/*.png
         - uses: jruipinto/ImageMagick-action@v1
           with:
              # ImageMagick command to be executed
              command: mogrify -resize x250 -format webp assets/img/galleries/*/*.jpeg
         - uses: jruipinto/ImageMagick-action@v1
           with:
              # ImageMagick command to be executed
              command: mogrify -resize x250 -format webp assets/img/galleries/*/*.png
         - name: Commit report
           run: |
              git config --global user.name 'Jasmine Chatfield'
              git config --global user.email 'jasminechatfield@users.noreply.github.com'
              git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
              git checkout "${GITHUB_REF:11}"
              git add .
              git commit -am "Thumbnails"
              git push
