name: Generate thumbnails

on:
   push:
      branches:
         - main

jobs:
   build:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v1
         - uses: jruipinto/ImageMagick-action@v1
           name: "Generate thumbnails of pages from jpegs"
           with:
              # ImageMagick command to be executed
              command: mogrify -resize x250 -format webp assets/img/pages/*/*.jpeg
         - uses: jruipinto/ImageMagick-action@v1
           name: "Generate thumbnails of pages from pngs"
           with:
              # ImageMagick command to be executed
              command: mogrify -resize x250 -format webp assets/img/pages/*/*.png
         - uses: jruipinto/ImageMagick-action@v1
           name: "Generate thumbnails of gallery images from jpegs"
           with:
              # ImageMagick command to be executed
              command: mogrify -resize x250 -format webp assets/img/galleries/*/*.jpeg
         - uses: jruipinto/ImageMagick-action@v1
           name: "Generate thumbnails of gallery images from pngs"
           continue-on-error: true
           with:
              # ImageMagick command to be executed
              command: mogrify -resize x250 -format webp assets/img/galleries/*/*.png
         - name: Commit generated thumbnails
           run: |
              git config --global user.name 'Jasmine Chatfield'
              git config --global user.email 'jasminechatfield@users.noreply.github.com'
              git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
              git checkout "${GITHUB_REF:11}"
              git commit --allow-empty -am "Thumbnails"
              git push
         - uses: actions/cache@v2
           with:
              path: vendor/bundle
              key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
              restore-keys: |
                 ${{ runner.os }}-gems-
         - uses: helaili/jekyll-action@v2
           with:
              token: ${{ secrets.GITHUB_TOKEN }}
