name: Generate thumbnails

on:
   push:
      branches:
         - main

jobs:
   build:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v1
         - uses: jruipinto/ImageMagick-action@v1
           with:
              # ImageMagick command to be executed
              command: mogrify -resize x250 -format webp assets/img/pages/*/*.jpeg
         - name: Trigger GitHub pages rebuild
           run: |
              curl --fail --request POST \
                --url https://api.github.com/repos/${{ github.repository }}/pages/builds \
                --header "Authorization: Bearer $USER_TOKEN"
           env:
              # You must create a personal token with repo access as GitHub does
              # not yet support server-to-server page builds.
              USER_TOKEN: ${{ secrets.USER_TOKEN }}
         - name: Commit report
           run: |
              git config --global user.name 'Jasmine Chatfield'
              git config --global user.email 'jasminechatfield@users.noreply.github.com'
              git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
              git checkout "${GITHUB_REF:11}"
              git commit -am "Thumbnails"
              git push
